Closes #86: Allow alternate identifiers to be used
open-cogsci/omm-server pull request #87
Opened 2021-04-12 20:54 UTC by dschreij

This is a rough working version of allowing alternate identifiers. Currently implemented:

- Endpoint `GET /participants/{identifier}/canonical` to retrieve the canonical identifier.
- UI elements for adding alternate identifiers to participants.
- Validation:
    -  Is the supplied identifier unique for both identifier and alternate_identifier fields? (there should be no duplicates in either column in the database) (NEEDS TO BE MORE THOROUGHLY TESTED)
    - Are the values of identifier and alternate_identifier in the form not the same?

TODOs:
- If the value of `alternate_indentifier` is `null`, it is shown as null in viewing panel, and the default value of the field in the edit panel also shows null. This of course should be empty in both cases (or ommited in the viewing panel).
- More @smathot ?

2021-04-12 20:59 UTC, dschreij commented
@smathot. If you try this out for a spin, don't forget to run `adonis migration:run` first as there are changes to the database.

2021-04-13 09:00 UTC, smathot commented
If I try to change the alternate identifier to anything other than 'null', then I get the following error message when pressing 'Save changes':

![image](https://user-images.githubusercontent.com/594936/114526400-3de59800-9c47-11eb-86c0-24731bea6dc5.png)

2021-04-13 13:28 UTC, dschreij commented
This is a CORS error, which happens if the front-end and the API_URL have a different hostname. I think you had it before? Back then you had 127.0.0.1 for one entry, and used localhost for the other. If you use either one for both then this should be fine again.

2021-04-14 10:25 UTC, smathot commented
You're right (as usual) :+1: I will implement this in the client and then let you know if it works as expected.

2021-04-15 11:13 UTC, smathot requested changes
It basically works, and I've implemented support for it in the client, but when you ask for a non-existent ID, the response is broken (see image below). This makes little practical difference, but still worth fixing.

![image](https://user-images.githubusercontent.com/594936/114860416-40352700-9dec-11eb-8b1d-532371bfe3ac.png)

2021-04-15 13:53 UTC, dschreij commented
That is the default 404 response :). You should receive this from any other endpoint where the record cannot be retrieved.
I think it is only this elaborate if you run in dev mode. If you run in production mode, the response should be more succinct. 

This is what I get at omm.cogsci.nl:

![image](https://user-images.githubusercontent.com/689044/114880394-50f09780-9e02-11eb-83bc-ecf1daf95355.png)

So basically the same, but without the frames/stack trace. The message could be nicer, but in practice, you will use the value of the `code` field anyway to use i18n for the error message, and never the message value directly.

I also found this ugly at first, and there is a catch-all solution that I wanted to implement (following https://adonisjs.com/docs/4.1/exceptions), but I never got to this because I didn't give it priority.

2021-04-15 13:55 UTC, smathot approved these changes

2021-04-15 13:56 UTC, merged